kind: Deployment
apiVersion: apps/v1
metadata:
  name: neoload-yaml-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neoload-yaml-generator
  template:
    metadata:
      labels:
        app: neoload-yaml-generator
    spec:
      containers:
        - name: neoload-yaml-generator
          image: ocp4-quay.arbetsformedlingen.se/testplattformar/neoload-yaml-generator:latest
          ports:
            - containerPort: 3001
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: https://neoloadutils-af-neoload-acc.apps.tocp4.arbetsformedlingen.se
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  progressDeadlineSeconds: 600
  paused: false